SOI_quantity_limit: 5
SOI_trigger_mode: '0'
SOI_trigger_time: 0
SOI_trigger_timeout: 10
buffer_size_interval: 2
clear_log_file_on_startup: true
dashboard_hiprfisr_dealer_port: 5051
dashboard_pub_port: 5057
disabled_running_flow_graph_variables:
- ip_address
- tx_usrp_channel
- rx_usrp_channel
- tx_usrp_antenna
- rx_usrp_antenna
- filepath
failure_multiple: 5
fft_sample_rate: 1e6
fft_size: 4096
fge_hiprfisr_dealer_port: 5053
fge_pub_port: 5061
hardware_archive: HackRF
hardware_attack: HackRF
hardware_daughterboard_archive: CBX
hardware_daughterboard_attack: CBX
hardware_daughterboard_iq: CBX
hardware_daughterboard_pd: CBX
hardware_daughterboard_tsi: CBX
hardware_interface_archive: ''
hardware_interface_attack: ''
hardware_interface_iq: ''
hardware_interface_pd: ''
hardware_interface_tsi: ''
hardware_ip_archive: ''
hardware_ip_attack: ''
hardware_ip_iq: ''
hardware_ip_pd: ''
hardware_ip_tsi: ''
hardware_iq: HackRF
hardware_pd: HackRF
hardware_serial_archive: 457863c823636f1f
hardware_serial_attack: 457863c823636f1f
hardware_serial_iq: 457863c823636f1f
hardware_serial_pd: 457863c823636f1f
hardware_serial_tsi: 457863c823636f1f
hardware_tsi: HackRF
heartbeat_interval: 5
hiprfisr_pub_port: 5055
morse_code_amplitude_threshold: 0.5
morse_code_between_letter_spacing: 3
morse_code_between_word_spacing: 7
morse_code_error_tolerance: 0.05
morse_code_same_letter_spacing: 1
moving_avg_points: 5
pd_bits_port: 5066
pd_hiprfisr_dealer_port: 5054
pd_pub_port: 5063
process_SOIs: 'False'
remember_configuration: 'False'
startup_automation_mode: Manual
target_SOI: 0
tsi_hiprfisr_dealer_port: 5052
tsi_pub_port: 5059
tsi_pub_port_classification: 5065
tsi_pub_port_id: 5060
